import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class AnalyticsCreate {
  @ApiProperty()
  result: string;
}

export class Analytics {
  @ApiProperty()
  id: number;
  @ApiProperty()
  result: string;
}
